SELECT TOP (1000) [customer_key]
      ,[customer_id]
      ,[customer_number]
      ,[first_name]
      ,[last_name]
      ,[country]
      ,[marital_status]
      ,[gender]
      ,[birthdate]
      ,[create_date]
  FROM [DataWarehouseAnalytics].[gold].[dim_customers_Analytics]


  -- Explore all objects in the Database
  SELECT * FROM INFORMATION_SCHEMA.TABLES


  -- Explore all columns in the Database
  SELECT * FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'dim_customers_Analytics'

  -- Explore All countries our customer come from

  SELECT DISTINCT country FROM gold.dim_customers_Analytics


  -- Explore All categories "The Major Divisions"

  SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products_Analytics
  ORDER BY 1,2,3

  -- Find the date of First and Last order

  SELECT 
  MIN(order_date) AS first_order_date,
  MAX(order_date) AS last_order_date,
  DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) AS order_range_years, -- How many years of sales are available
  DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS order_range_months
  FROM gold.fact_sales


  -- Find the youngest and oldest customer

SELECT
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers_Analytics


-- Measures
-- Find the Total Sales
SELECT SUM(sales_amount) AS total_Sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) AS total_Quantity FROM gold.fact_sales

-- Find the average sellling price
SELECT AVG(price) AS Avg_price FROM gold.fact_sales

-- Find the Total number of Orders
SELECT COUNT(order_number) AS Total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT(order_number)) AS Total_orders FROM gold.fact_sales

-- Find the Total number of products
SELECT COUNT(product_key) AS Total_products FROM gold.dim_products_Analytics
SELECT COUNT(DISTINCT(product_key)) AS Total_products FROM gold.dim_products_Analytics

--OR


SELECT COUNT(product_name) AS Total_products FROM gold.dim_products_Analytics
SELECT COUNT(DISTINCT(product_name)) AS Total_products FROM gold.dim_products_Analytics

-- Find the Total number of Customers
SELECT COUNT(customer_key) AS Total_customers FROM gold.dim_customers_Analytics;


-- Find the Total number of Customers that has placed an order
SELECT COUNT(DISTINCT(customer_key)) AS Total_customers_PlacedOrder FROM gold.fact_sales;


-- Generate a Report that shows all key metrics of the business

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Qunaity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total No.of Orders', COUNT(DISTINCT(order_number)) FROM gold.fact_sales
UNION ALL
SELECT 'Total No.of Products', COUNT(product_name) FROM gold.dim_products_Analytics
UNION ALL
SELECT 'Total No.of Customers', COUNT(customer_key) FROM gold.dim_customers_Analytics


-- Magnitude Analysis

-- Find total customer by countries
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers_Analytics
GROUP BY country
ORDER BY total_customers DESC

-- Find total customer by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers_Analytics
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products_Analytics
GROUP BY category
ORDER BY total_products DESC


-- What is the average costs in each category?
SELECT
category,
AVG(cost) AS Avg_costs
FROM gold.dim_products_Analytics
GROUP BY category
ORDER BY Avg_costs DESC

-- What is the total revenue generated for each category?

USE DataWarehouseAnalytics
SELECT
p.category,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products_Analytics p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC



-- What is the total revenue generated by each customer?
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers_Analytics c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC


-- What is the distribution of sold items across countries?

SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers_Analytics c
ON f.customer_key = c.customer_key
GROUP BY
c.country
ORDER BY
total_sold_items DESC


-- Which 5 products generate the highest revenue?

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products_Analytics p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_sales DESC


-- which are the 5 worst-performaing products in terms of sales?

SELECT TOP 5
p.product_name,
SUM(f.sales_amount) AS total_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products_Analytics p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_sales

-- Using Window fucntion for more conplex data analysis

SELECT
* FROM
(SELECT
p.product_name,
SUM(f.sales_amount) AS total_sales,
ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_products_Analytics p
ON p.product_key = f.product_key
GROUP BY p.product_name)t
WHERE rank_products <=5

-- Find the top 10 customers who have generated the highest revenue

SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers_Analytics c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue

-- The 3 customers with the fewest orders placed

SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers_Analytics c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders